### ISSUE TITLE
Support shell language

### ISSUE THREAD

**Issue by dougmet** [MangoTheCat/rcloud.jupyter.notebooks#2]
In the `cellLanguage` function what happens if you have a `.sh` shell script?

https://github.com/MangoTheCat/rcloud.jupyter.notebooks/blob/301d237b1a74548683f096033fc65102611cd18d/R/export_jupyter.R#L117

We should add in a `.sh` option and think about what happens if it's something else. For example: A Julia cell (not supported in RCloud but it supported in Jupyter) would be a `.jl` file. I wonder if having a little lookup would be useful? Just for the major 5/6 languages.

See here for the ridiculously complete list of languages that GitHub understands by file extension 
https://github.com/github/linguist/blob/c8ca48856b1998681cdf1c1234145532006f95d8/lib/linguist/languages.yml

**Comment by dougmet** [comment]
Hi @bashlee , this got a little rambly, we can discuss when I next see you!

**Comment by bashlee** [comment]
Feature to support shell script push to develop branch
