### ISSUE TITLE
remove %load_ext rpy2.ipython when importing from jupyter notebook

### ISSUE THREAD

**Issue by gordonwoodhull** [MangoTheCat/rcloud.jupyter.notebooks#8]
I know it's probably annoying to have special cases like this, but wherever possible, we should try to produce the same notebook when round-tripping from RCloud to Jupyter and back again.

One of the use cases for this package is exporting a notebook to try it out in Jupyter or perform any steps that can't be done in RCloud, and then bringing it back to share with colleagues.

One case where the notebook changes when round-tripping is the special 

```python
%load_ext rpy2.ipython
```

cell that is added when there are R cells in the notebook. When importing the Jupyter notebook back, this cell should be removed. (It doesn't make sense in RCloud because you'd never want to run R within a Python cell, or if you do, you're crazy.)

I suppose the clever thing to do would be to remove just the line, and then remove the cell if it's empty, but I'm fine with just removing a cell that only contains that content, since that will be the common case.

This will never be perfect, but we just want to minimize hassle for people who use the package this way.

**Comment by gordonwoodhull** [comment]
Another reason to remove it is that if you round-trip a second time, you end up with two of these cells. Etc.

**Comment by bashlee** [comment]
%load_ext rpy2.ipython removed and if resulting cell content is blank cell also removed. This should avoid any lines being lost if user has added to cell or merged it with another.
