### ISSUE TITLE
R cells start with a blank line when imported from a mixed-language notebook

### ISSUE THREAD

**Issue by gordonwoodhull** [MangoTheCat/rcloud.jupyter.notebooks#9]
When importing a mixed-language jupyter notebook, the R cells end up with a blank line at a top. (Or if round-tripped twice, two blank lines, etc.)

This only happens when the notebook contains multiple languages, not for a pure-R notebook. Presumably the `%%R` magic is removed, but not the newline.

**Comment by bashlee** [comment]
Fix pushed to develop.
